[package]
name = "indicator_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.123", default-features = false, features = ["derive"] }
postcard = { version = "1.0.4", default-features = true }
